<?php 	
	define('HOSTNAME_DATABASE', 'localhost');
	define('USERNAME', 'root');
	define('PASSWORD', '123456');
	define('DATABASE', 'moviliaria'); 	 
	define('URL_BASE', '/moviliaria/');
	define('PATH_MODELS', PATH_ROOT."/app/models");
	define('PATH_CONTROLLERS', PATH_ROOT."/app/controllers");
	define('PATH_VIEWS', PATH_ROOT."/public/views");
	define('PATH_BASE', "/moviliaria");	
	define('PATH_CSS', PATH_BASE."/web/css");
	define('PATH_JS', PATH_BASE."/web/js");
	define('PATH_IMAGES', PATH_BASE."/web/images");
	define('PATH_TEMPLATE', PATH_ROOT."/template");
	define('PATH_HELPERS', PATH_BASE."/lib");
	define('PATH_FILES', PATH_ROOT."/../web");
	
	
?>